# Generated by Django 5.0.6 on 2024-07-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenesMovilizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencial_orden_movilizacion', models.CharField(max_length=50)),
                ('fecha_hora_emision', models.DateTimeField()),
                ('fecha_desde', models.DateField()),
                ('hora_desde', models.TimeField()),
                ('fecha_hasta', models.DateField()),
                ('hora_hasta', models.TimeField()),
                ('habilitado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ordenes_movilizacion',
                'managed': False,
            },
        ),
    ]
