# Generated by Django 5.0.6 on 2024-07-19 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdenesMovilizacion', '0003_motivoordenmovilizacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleados',
        ),
    ]
