# Generated by Django 5.0.6 on 2024-08-26 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdenesMovilizacion', '0004_delete_empleados'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioOrdenMovilizacion',
            fields=[
                ('id_horario_movilizacion', models.AutoField(primary_key=True, serialize=False)),
                ('hora_ida_minima', models.TimeField()),
                ('hora_llegada_maxima', models.TimeField()),
                ('duracion_minima', models.IntegerField()),
                ('duracion_maxima', models.IntegerField()),
            ],
            options={
                'db_table': 'horario_orden_movilizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RutasMovilizacion',
            fields=[
                ('id_ruta_movilizacion', models.AutoField(primary_key=True, serialize=False)),
                ('ruta_origen', models.CharField(max_length=250)),
                ('ruta_destino', models.CharField(max_length=250)),
                ('ruta_descripcion', models.CharField(max_length=250)),
                ('ruta_estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'rutas_movilizacion',
                'managed': False,
            },
        ),
    ]
