# Generated by Django 5.0.6 on 2024-07-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(max_length=100)),
                ('siglas_unidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'unidades',
                'managed': False,
            },
        ),
    ]
