# Generated by Django 5.0.6 on 2024-06-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasBienes',
            fields=[
                ('id_categorias_bien', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorias_bienes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubcategoriasBienes',
            fields=[
                ('id_subcategoria_bien', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('identificador', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'subcategorias_bienes',
                'managed': False,
            },
        ),
    ]
