# Generated by Django 5.0.6 on 2024-07-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0002_delete_cargos_delete_estaciones_delete_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoEmpleados',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.DO_NOTHING, to='Empleados.empleados')),
            ],
            options={
                'db_table': 'motivo_empleados',
            },
        ),
    ]
