# Generated by Django 5.0.6 on 2024-07-06 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id_informes', models.AutoField(primary_key=True, serialize=False)),
                ('secuencia_informe', models.IntegerField(blank=True, null=True)),
                ('fecha_informe', models.DateField(blank=True, null=True)),
                ('fecha_salida_informe', models.DateField(blank=True, null=True)),
                ('hora_salida_informe', models.TimeField(blank=True, null=True)),
                ('fecha_llegada_informe', models.DateField(blank=True, null=True)),
                ('hora_llegada_informe', models.TimeField(blank=True, null=True)),
                ('evento', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'informes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('distintivo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('habilitado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('id_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estacion', models.CharField(max_length=100)),
                ('siglas_estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'estaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cedula', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductosAlcanzadosInformes',
            fields=[
                ('id_producto_alcanzado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos_alcanzados_informes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField()),
                ('motivo_movilizacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_salida_solicitud', models.DateField(blank=True, null=True)),
                ('hora_salida_solicitud', models.TimeField(blank=True, null=True)),
                ('fecha_llegada_solicitud', models.DateField(blank=True, null=True)),
                ('hora_llegada_solicitud', models.TimeField(blank=True, null=True)),
                ('descripcion_actividades', models.TextField(blank=True, null=True)),
                ('listado_empleado', models.TextField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'solicitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporteInforme',
            fields=[
                ('id_transporte_informe', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transporte_info', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_transporte_info', models.CharField(blank=True, max_length=100, null=True)),
                ('ruta_info', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_salida_info', models.DateField(blank=True, null=True)),
                ('hora_salida_info', models.TimeField(blank=True, null=True)),
                ('fecha_llegada_info', models.DateField(blank=True, null=True)),
                ('hora_llegada_info', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transporte_informe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransporteSolicitudes',
            fields=[
                ('id_transporte_soli', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_transporte_soli', models.CharField(blank=True, max_length=50, null=True)),
                ('ruta_soli', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_salida_soli', models.DateField(blank=True, null=True)),
                ('hora_salida_soli', models.TimeField(blank=True, null=True)),
                ('fecha_llegada_soli', models.DateField(blank=True, null=True)),
                ('hora_llegada_soli', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transporte_solicitudes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidades',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_unidad', models.CharField(max_length=100)),
                ('siglas_unidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'unidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesInformes',
            fields=[
                ('id_informe', models.OneToOneField(db_column='id_informe', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Informes.informes')),
                ('dia', models.DateField(blank=True, null=True)),
                ('actividad', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'actividades_informes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturasInformes',
            fields=[
                ('id_informe', models.OneToOneField(db_column='id_informe', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Informes.informes')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('detalle_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'facturas_informes',
                'managed': False,
            },
        ),
    ]
