# Generated by Django 5.1 on 2024-08-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0002_bancos_categoriasbienes_cuentasbancarias_motivo_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provincias',
                'managed': False,
            },
        ),
    ]
