# Generated by Django 5.0.6 on 2024-09-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0003_ciudades_provincias'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalFactura',
            fields=[
                ('id_total', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'total_factura',
                'managed': False,
            },
        ),
    ]
