# Generated by Django 5.0.6 on 2024-09-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0004_totalfactura'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoFactura',
            fields=[
                ('id_estadofactura', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField(choices=[(0, 'incompleto'), (1, 'completo')])),
            ],
            options={
                'db_table': 'estado_factura',
                'managed': False,
            },
        ),
    ]
