# Generated by Django 5.0.6 on 2024-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasBienes',
            fields=[
                ('id_categorias_bien', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'categorias_bienes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubcategoriasBienes',
            fields=[
                ('id_subcategoria_bien', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('identificador', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'subcategorias_bienes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id_vehiculo', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20)),
                ('codigo_inventario', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('color_primario', models.CharField(blank=True, max_length=50, null=True)),
                ('color_secundario', models.CharField(blank=True, max_length=50, null=True)),
                ('anio_fabricacion', models.IntegerField(blank=True, null=True)),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('habilitado', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
    ]
