# Generated by Django 5.0.6 on 2024-07-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoVehiculo',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_vehiculo', models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.DO_NOTHING, to='Vehiculos.vehiculo')),
            ],
            options={
                'db_table': 'motivo_vehiculo',
            },
        ),
    ]
