# Generated by Django 5.0.6 on 2024-08-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encabezados',
            fields=[
                ('id_encabezado', models.AutoField(primary_key=True, serialize=False)),
                ('encabezado_superior', models.TextField(blank=True, null=True)),
                ('encabezado_inferior', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'encabezados',
                'managed': False,
            },
        ),
    ]
